version: 2
updates:
  - package-ecosystem: 'devcontainers'
    directory: '/'
    schedule:
      interval: weekly

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: daily
    ignore:
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-major']
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: weekly
    ignore:
      - dependency-name: 'node'
        update-types: ['version-update:semver-major']
    labels:
      - 'docker'
      - 'dependencies'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily

versioning-strategy: 'auto'
commit-message:
  prefix: 'dependabot'
  include: 'scope'
