ignores:
  [
    '@commitlint/*',
    '@typescript-eslint/*',
    'commitizen',
    'depcheck',
    'prettier',
    'prettier-*',
    'autoprefixer',
    'postcss',
    'tailwindcss',
    'tailwindcss-animated',
    'axios',
    'zod',
    'react-icons',
  ]
skip-missing: true
