ignores:
  [
    '@commitlint/*',
    '@typescript-eslint/*',
    'commitizen',
    'depcheck',
    'prettier',
    'prettier-*',
    'autoprefixer',
    'postcss',
    'tailwindcss',
    'tailwindcss-animated',
    'react-gtm-module',
    '@types/react-gtm-module',
  ]
skip-missing: true
